# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_my_ajax

test:
  <<: *default
  database: test_my_ajax

production:
  <<: *default
  database: production_my_ajax
  username: postgres
  password: password
